
DROP TABLE CLAIM CASCADE;

CREATE TABLE CLAIM
(
	CLAIM_ID INTEGER NOT NULL ,
	MEMBER_ID INTEGER NULL ,
	PROVIDER_ID INTEGER NULL ,
	CLAIM_DATE DATE NULL ,
	CLAIM_STATUS VARCHAR(20) NULL ,
	CLAIM_AMOUNT DECIMAL(12,2) NULL ,
	PAID_AMOUNT DECIMAL(12,2) NULL ,
	DEL_INDC VARCHAR(20) NULL 
);
