
DROP TABLE PROVIDER_SPECIALTY CASCADE;

CREATE TABLE PROVIDER_SPECIALTY
(
	SPECIALTY_ID INTEGER NOT NULL ,
	SPECIALTY_NAME VARCHAR(50) NULL ,
	SPECIALTY_DESCRIPTION VARCHAR(50) NULL ,
	DEL_INDC VARCHAR(20) NULL ,
	CRE_USR_DT DATE NULL ,
	CRE_USR_ID VARCHAR(20) NULL 
);

ALTER TABLE PROVIDER_SPECIALTY
	ADD CONSTRAINT XPKPROVIDER_SPECIALTY PRIMARY KEY (SPECIALTY_ID);
